### ISSUE TITLE
Reset sensor orientation required.

### ISSUE THREAD

**Issue by ChrisDenham** [bjornblissing/osgoculusviewer#52]
Since updating to the 0.6.0.1 version, I've noticed that I seem to need to call  OculusDevice::resetSensorOrientation() i.e. ovrHmd_RecenterPose(m_hmdDevice); every time I restart my application because the default orientation seems to be different from the recentered pose.
Am I doing something wrong? Or do we need to add an explicit call to recenter pose on application/viewer startup?

**Comment by bjornblissing** [comment]
In the 1.3 SDK there is a new function `ovr_GetSessionStatus::ShouldRecenter` which should be used to trigger `ovr_RecenterTrackingOrigin` when needed.

**Comment by bjornblissing** [comment]
Unable to reproduce the error using the current version of the Oculus SDK (1.20.0).
