### ISSUE TITLE
Cannot find Oculus debug libraries during CMake configuration

### ISSUE THREAD

**Issue by lpsandaruwan** [bjornblissing/osgoculusviewer#65]
I'm trying to build "osgoculusviewer" using, msvc 10, cmake 3.3.1, osg 3.0.1 and oculus sdk 0.7.0.0. And I'm getting this error while configuring cmake. Will be grateful for help. Thank you.
![untitled](https://cloud.githubusercontent.com/assets/5220773/9901778/665278f4-5c87-11e5-9392-a141dee1ed2f.png)

**Comment by ChrisDenham** [comment]
Did you point CMAKE at your oculus SDK installation location?
I think if you setup an environment variable e.g.:
`OCULUS_SDK_ROOT_DIR=C:\OculusSDK`
it should work ok.

**Comment by lpsandaruwan** [comment]
Yes. I did set the SDK location. But it didn't work.

**Comment by bjornblissing** [comment]
Check if you have built the Oculus debug libraries. For some reason the Oculus SDK only comes with prebuilt libraries for release version.

But you can build them yourself by opening the following solution and build the debug version of libOVR:
`OculusSDK\v0.7.0.0\Samples\Projects\Windows\VS2010\Samples.sln`

**Comment by lpsandaruwan** [comment]
Thank you very much, I'll try that.

**Comment by bjornblissing** [comment]
I will see if I can modify the CMAKE script so that it won't require you to build the debug version and instead link to the release version, if no debug library is present.
