### ISSUE TITLE
 RTT cameras jitter with DrawThreadPerContext model

### ISSUE THREAD

**Issue by west036** [bjornblissing/osgoculusviewer#79]
I use NodeTrackerManipulator in the scene to make the main camera tracking a flying plane, when I use the DrawThreadPerContext model, RTT cameras will jitter, especially the left RTT, this phenomenon seems to be slave cameras update before the master camera occasionally, resulting in non synchronization.
When using SingleThreaded model, there is no jitter, I also notice the SingleThreaded is forced to use in viewerexample,but the frame rate will be significantly reduced with this model. Is there anyway to fix this issue.

**Comment by bjornblissing** [comment]
All threading modes but ```SingleThreaded``` will introduce one frame of added latency. Which is why you are seeing jitter while using ```DrawThreadPerContext```.

See: http://forum.openscenegraph.org/viewtopic.php?p=62642#62642
