### ISSUE TITLE
crashes with intel HD 5000 + i7-4650u + 8gb ram + windows 10

### ISSUE THREAD

**Issue by xinbada007** [bjornblissing/osgoculusviewer#84]
Commit: e2447e5515674377fd8aec71c050d211f18828e2
OculusSDK: 0.8.0.0 with DK2

When trying to run my program on a laptop with Intel HD5000 + i7-4650u + 8gb ram + win10, it breaks at the following point:
Cpp File: oculusdevice.cpp
Function: OculusMirrorTexture::OculusMirrorTexture
Breakpoint: fbo_ext->glFramebufferTexture2D(GL_READ_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, m_texture->OGL.TexId, 0);
It says unhanded exception at blah...blah...blah...

However, my program runs fine on a desktop with GTX640 + i5 + 4gb ram + win7. I have also tried to run the oculusviewer example program and got the same result. The example program crashes with intel graphics but works with nvidia one. Interestingly, the official oculus example programs do not have this issue, they work fine on both computers.

Any idea. Perhaps you guys used some platform-specific opengl extension or things like that?

**Comment by xinbada007** [comment]
Updates: spared some time to debug the code using oculusviewer example program. I found that the struct "m_texture" is NULL when passing to glFramebufferTexture2D. Probably it is not created successfully???

**Comment by xinbada007** [comment]
last update: OK guys. seems like not your problem. I have tried official example programs (tinyroom, worlddemo). These program only works with DirectX, the GL version crashes as well. I guess OculusSDK implemented some wired OpenGL things.

**Comment by bjornblissing** [comment]
Hi @xinbada007 

The Intel Graphics cards are not officially supported by Oculus, neither are most laptops.
https://www.oculus.com/en-us/blog/powering-the-rift/
