### ISSUE TITLE
Enable change of mirror texture size

### ISSUE THREAD

**Issue by rickyviking** [bjornblissing/osgoculusviewer#85]
At the moment the mirror texture size is hard-coded to half of the Oculus screen size.
I'd like to submit a pull request exposing a way to set it.
Just a couple of questions to use as guidelines:
- should I specify the mirror tex size as percentage of the Oculus screen size or explicitly in pixels (for the mirror width, with the height computed accordingly to the Oculus ar) ?
- I would probably expose it as an extra parameter in the OculusDevice ctor, is that ok with you?

**Comment by bjornblissing** [comment]
I think that a specifying in pixel size is preferable. 

And exposing it in the constructor would probably be the simplest way of doing. I would suggest that you add some default values.

**Comment by rickyviking** [comment]
I've submitted the pull request: https://github.com/bjornblissing/osgoculusviewer/pull/86
It is based on the branch sdk-v0.8 which I'm currently using, but cherry picking to master should work as well.

**Comment by bjornblissing** [comment]
Merged to 0.8, 1.3, 1.4 and master branch.
