### ISSUE TITLE
your OSG version?

### ISSUE THREAD

**Issue by sczhaoyu** [bjornblissing/osgoculusviewer#87]
your OSG version?

visual studio  version ?

**Comment by bjornblissing** [comment]
I personally use Visual Studio 2015 with OSG 3.4.0. But I think this project works with the 3.2 branch as well.

Are you having problems compiling?

**Comment by sczhaoyu** [comment]
No problem,Thanks.

**Comment by bjornblissing** [comment]
So why do you ask??

**Comment by sczhaoyu** [comment]
Because I have a glass frame on the screen,I don't know how to cancel.

**Comment by bjornblissing** [comment]
Sorry, I have no clue what you are talking about...
