### ISSUE TITLE
Jitter in Oculus CV1

### ISSUE THREAD

**Issue by CambridgePark** [bjornblissing/osgoculusviewer#89]
I compiled the OculusViewerExample.exe and when I run it the cow displays, but there is considerable jitter when I move my head (Oculus CV1). The jitter is not present on the computer monitor view, only in the Oculus itself. Wondering if anyone else is seeing this issue. If yes, is this a code issue or computer system issue.

**Comment by bjornblissing** [comment]
Make sure that you have not forced V-sync off in the graphics driver settings.

**Comment by bjornblissing** [comment]
@CambridgePark Did my suggestion help your Jitter issues?

**Comment by CambridgePark** [comment]
The V-Sync is on and there is still jitter.

**Comment by bjornblissing** [comment]
@CambridgePark V-Sync should **NOT** be enabled.

The default settings for most graphic cards is to have this setting application controlled. If if set like that then OsgOculusViewer will handle the disabling of vsync automatic. BUT if you have forced V-sync ON then you will get jitter.

Other common jitter sources is that the computer is not powerful enough for the geometry you are displaying. Press `1`, `2`, `3`, and `4` on the keyboard for detailed render information.

**Comment by bjornblissing** [comment]
@CambridgePark did you solve your jitter issues?

**Comment by bjornblissing** [comment]
Closed due to lack of information.
