### ISSUE TITLE
SOS：my frame falls down really quick！

### ISSUE THREAD

**Issue by sczhaoyu** [bjornblissing/osgoculusviewer#91]
When I'm integrating VR glasses in OSG, the frame falls down sharply from 120 to 45.
I'm integrating the project of flightgear, and I met performance bottleneck.
thw problem i met was picture tremble, the infrared locator doesn't work at USB3.0.
The biggest problem is the reduce of rendering frame rate.

**Comment by sczhaoyu** [comment]
My Oculus SDK 1.10.1 i hope to make optimization.

**Comment by bjornblissing** [comment]
Did this problem start when you updated to Oculus SDK 1.10.1?

**Comment by sczhaoyu** [comment]
My Oculus SDK's version is 1.10.1.
Oculus APP Version Update to the latest。
This version has a delay problem both on locator and head sensor. It could make picture  chattering and flicker. Could you please resolve it?

**Comment by bjornblissing** [comment]
The only difference between this version of the Oculus SDK and the previous is that Asynchronous Spacewarp have been enabled as default. Maybe this is something that you need to disable. Although I have no information if it is possible nor how to do it.
