### ISSUE TITLE
Can't see  screen  statis 

### ISSUE THREAD

**Issue by sczhaoyu** [bjornblissing/osgoculusviewer#92]
Hell   bjornblissing:
   Press S key, Can't see  screen  statis.

**Comment by sczhaoyu** [comment]
@bjornblissing

**Comment by bjornblissing** [comment]
@sczhaoyu the statistics are available by pressing: 1, 2, 3, 4 on the keyboard. Press 0 to remove the statistics view.

**Comment by sczhaoyu** [comment]
thanks
