### ISSUE TITLE
Where to put cow.osgt ?

### ISSUE THREAD

**Issue by KikoVR** [bjornblissing/osgoculusviewer#93]
Hi Bjorn,

Really sorry in advance for this nerd question but I am quite new to OSG..

I have actually built your OculusViewerExample with Oculus SDK 1.6 as it was the last tested, and I have the following message : `No model could be loaded and didn't find cow.osgt, terminating..`

I've tried to put the cow.osgt in the same folder than the .exe file, but nothing better..

I actually don't know where the osgDB::readNodeFile function is looking into..

Thank you very much in advance for any help that can be provided.

Best regards

**Comment by bjornblissing** [comment]
@KikoVR Can you load the cow model with standard osgviewer? 

Usually when models refuse to load there is some problem with either the path or the file reader plugins.

**Comment by KikoVR** [comment]
Hi Bjorn,

Actually, no... (I discovered this after)

I am actually trying to solve that problem, which is strange because my
PATH is correctly set (I guess).

Thanks for your answer


2017-10-11 11:33 GMT+02:00 Björn Blissing <notifications@github.com>:

**Comment by ChrisDenham** [comment]
Have you tried using the full path of the osg file, or dragging cow.osg on to osgviewer.exe? If that works then you probably just need to define the OSG_FILE_PATH environment variable to point at the folder location. If it doesn't work, it may mean you are missing the osg plugin required to load that file type.

**Comment by KikoVR** [comment]
Hi,

Thank you for your answer.

I tried copying cow.osg to the folder of osgviewer.exe but this did not
change anything. However, after adding PATH variables as you suggested, it
works ! And then, I was also able to build and use the OculusViewerExample.

Thank you very much !

Best regards

2017-10-19 10:29 GMT+02:00 ChrisDenham <notifications@github.com>:

**Comment by ChrisDenham** [comment]
cool. 
btw. when i suggested dragging cow.osg to osgviewer.exe, I meant on to the exe itself, i.e. not copying the file but launching osgviewer with the full path of cow.osg as a parameter. usually works on windows at least.
