### ISSUE TITLE
Distorted image when bending the head on a side

### ISSUE THREAD

**Issue by KikoVR** [bjornblissing/osgoculusviewer#94]
Hi,

I've been integrating your work into an existing 3D application based on OSG (with hundreds of child in the scene graph)
I have good results, but for some reason, I noticed the following :
- Image are flattened horizontally (not vertically)
- When bending the head on a side, the models are getting distorted (if I bend left, all vertical lines also bend left)

I don't experiment those problems with the simple viewerexample.. So I guess it might be coming from my integration of your work.

From the symptom, do you have any simple idea of what I might be doing wrong ?

Thanks

**Comment by bjornblissing** [comment]
Sorry, I do not. 

My best guess is that you are doing something wrong with your view matrix. But it is hard to say what. Try posting to the OpenSceneGraph forum. Describe your problem in detail and include a screenshot. Hopefully someone can help you further.
