### ISSUE TITLE
Error in eyes offset ?

### ISSUE THREAD

**Issue by KikoVR** [bjornblissing/osgoculusviewer#96]
Hi,

When I try to integrate osgoculus viewer in my own app, I have a very uncomfortable feeling that my left eye and right eye are significantly inverted in the HMD. 

I did not remember I had this feeling with the viewer example and the cow.

However, when looking more carefully to the viewerexample with the cow, I tried to close one eye, and then the other. I also tried to approach the moment when the head is entering into the cow, and you can see that my left eye is actually "entering the cow" first, before my right eye. Cf screenshot below : 

![leftright](https://user-images.githubusercontent.com/32293176/33272184-b577fc6c-d389-11e7-8194-45d8f08830d8.PNG)

The effect is slighter than what I have in my own app, but it is here.

So I guess there is a little problem in the code with the offsets or something else..

Sorry I don't have the skills to investigate further more..

**Comment by bjornblissing** [comment]
This looks really weird. I will have to dig into this to see if I can reproduce the error.

Some quick questions:
- Are you using the latest commit of osgoculusviewer?
- Which version of the Oculus SDK are you compiling against?
- Are you running this on a consumer version of the Oculus Rift (aka. CV1)?

**Comment by KikoVR** [comment]
Thanks for the feedback !

Actually I was not chocked about this when using the cow example i.e. I
thought the image was correct although I felt a little something strange.
This is only when trying to look into more details because of the problem I
have in my app that I could put this in evidence.

Yes I am using last version of osgoculus, Oculus SDK 1.17, and running a
consumer version of the Rift.

Le 27 nov. 2017 20:53, "Björn Blissing" <notifications@github.com> a écrit :

This looks really weird. I will have to dig into this to see if I can
reproduce the error.

Some quick questions:

   - Are you using the latest commit of osgoculusviewer?
   - Which version of the Oculus SDK are you compiling against?
   - Are you running this on a consumer version of the Oculus Rift (aka.
   CV1)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bjornblissing/osgoculusviewer/issues/96#issuecomment-347305915>,
or mute the thread

**Comment by KikoVR** [comment]
Hi Bjorn,

Have you got any time to try to reproduce this ?

I just wanted to tell you that I realized that this effect was hardly noticeable for object in the background, far from the camera, but that this is really strong when the object is near the eyes of the user.

So the effect is actually the same in the viewer example and in my app, but it just looks stronger in my app because of the fact there are a lot of objects in the foreground, at less than 1 meter from the eyes.

Best regards

**Comment by bjornblissing** [comment]
I have been able to reproduce this error. This is definitively a bug.

**Comment by KikoVR** [comment]
OK. I tested back with you previous code (before the recent update) and SDK Oculus 1.6 (last SDK supported before) and I could not reproduce this.

So this looks really linked to the recent update

**Comment by bjornblissing** [comment]
Since Oculus SDK 1.17 the EyeOffset is no longer a pure translation. Instead you receive a full pose structure, i.e. both translation and orientation. I suspect that something goes wrong when OsgOculusViewer applies this struct.

**Comment by KikoVR** [comment]
Maybe this is linked to what you just wrote, but I just found an additional "weird" behavior.

Not only my eyes are "inverted", as explained above, but also there seem to be a problem with orientation because for instance, my right eye view, which gives me the impression to be actually more left than my left eye view, have actually a further FOV on the right as you can see on the screenshot below.

![fovleftright](https://user-images.githubusercontent.com/32293176/33476882-d78b8b64-d683-11e7-95a2-8d96288fe841.PNG)

So if a camera placed further on the left sees further on the right, I guess there is either a problem of orientation, or this camera is actually offset in the back.

**Comment by ChrisDenham** [comment]
Not sure if this is relevant, but flipped eye offset problem rang some bells, so I wondered if the problem was in any way connected with #66 ?

**Comment by bjornblissing** [comment]
Well I have looked into the problem. A I cannot really see the error right now.

The response from the `ovr_CalcEyePoses()` gives me zero rotation of the eyes and the position offset only adjusted for the X-axis; negative for the left eye and positive for the right eye. Which should correlate with the OpenGL coordinates.

I guess I have to start dig deeper. The OpenGL example (*OculusRoomTiny(GL)*) provided in the OculusSDK do not use `ovr_CalcEyePoses()`, instead it uses `ovr_GetEyePoses()`. I have to try to decode the differences between them.

**Comment by bjornblissing** [comment]
I just compared the resulting view matrix from the 1.10 version of OsgOculusViewer to the present on. And the only difference is the negated translations of the eye offset. So a quick fix should be to just negate the values.

**Comment by bjornblissing** [comment]
I think I need to do some major refactoring to be able to use the same solution as the *OculusRoomTiny(GL)* example. So I will commit the quick fix as an interim solution.

**Comment by KikoVR** [comment]
Hi Bjorn,

Thank you so much for your reactivity.

I'll try it right now.

Best regards

**Comment by bjornblissing** [comment]
Hi @KikoVR 

I have changed how the view and projection matrix are built. Now I am mimicking the *OculusRoomTiny(GL)* example and use `ovr_GetEyePoses()`, instead of `ovr_CalcEyePoses()`.

By doing this I could remove a lot of code minimizing the room for error. And I think it looks correct. But it would be great if you could check it as well.

This change has been commited as: 05f9d63879079b21977afefac80ebd41ab13cb86

**Comment by KikoVR** [comment]
Hi Bjorn,

Sorry for the delay.

I will check by tomorrow and come back to you with my observations.

Thanks



2017-12-05 16:24 GMT+01:00 Björn Blissing <notifications@github.com>:

**Comment by KikoVR** [comment]
Hi Bjorn,

I checked and it is working fine for me !

I noticed 2 minor things :
- the view for each eye looks much less different than before. Indeed, if
you compared the 2 eyes previously, there was a big difference due to
ey-offset. Right now, the 2 images for Left and Right eye really look to be
the same (as if the IPD were really low). I cannot say if it is better or
worst, I just noticed this small difference
- the small app showing the 2 views from each eye are now showing not
distorted data (whereas it was previously distorted), I guess you changed
something here also right ?

Thanks again for your work and share

Best regards,


2017-12-13 10:02 GMT+01:00 Mehdi El Kouch <mehdi.elkouch@gmail.com>:

**Comment by bjornblissing** [comment]
Well, I do agree that the eye separation seems very small. It do not really seem right. I suspect that something gets scaled wrong, but I cannot really track down the reason for this. *(To make matters worse, my Rift unit broke the other day. So right now I am unable to test anything. Currently waiting for Oculus to process my RMA)*.

But I think that I will reopen this issue and try to solve it as soon as I get a working HMD.

Regarding the undistorted view on the normal monitor. This is a new feature which came with the Oculus SDK 1.20.0. If you prefer the old distorted version, just change `ovr_CreateMirrorTextureWithOptionsGL` to `CreateMirrorTextureGL`. 

The diff can be seen here:
https://github.com/bjornblissing/osgoculusviewer/commit/a397a2739917ce1e247fa9656fd46348e51fd0b6#diff-980aeb2be142b6a46c58e2a4a90500bfL325

**Comment by bjornblissing** [comment]
I have fixed this issue in both the master branch and in the 1.19.0 branch.

The reason for this error was that the eye offset (IPD) was canceled out due to applying inverse of the translation and orientation from the `getEyeRenderDesc()` function, then applying the translation and orientation from the `ovr_GetEyePoses()` function. This resulted in the IPD being very close to zero.

The result from the `getEyeRenderDesc()` function should **not** be used to calculate the view matrix. It should only be used as an input parameter to the `ovr_GetEyePoses()` function.

**Comment by KikoVR** [comment]
Hi Bjorn,

Sorry for my late reply. Just wanted to tell you I tested it and it works
fine !

Now the IPD is indeed more remarkable and the overall experience better.

Thanks again for your work

Best regards,

2018-01-01 19:23 GMT+01:00 Björn Blissing <notifications@github.com>:
